apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: huntmail
  namespace: huntmail
  labels:
    app: huntmail
  annotations:
    route.openshift.io/termination: edge
spec:
  ingressClassName: openshift-default
  rules:
    - host: huntmail.coderift.fun
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: huntmail
                port:
                  name: http
