apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: huntmail-data
  namespace: huntmail
  labels:
    app: huntmail
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
